version: "2.1"

services:

  plone:
    image: "$BACKEND_IMAGE:?no such variable"
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
      - zeo
      - memcached
    ports:
      - "8085:8080"
    environment:
      TZ: "Europe/Copenhagen"
      ZEO_ADDRESS: "zeo:8080"
      ZOPE_MODE: "zeo_client"

  frontend:
    image: "$FRONTEND_IMAGE:?no such variable"
    environment:
      RAZZLE_API_PATH: "http://localhost:8085/Plone"
      RAZZLE_INTERNAL_API_PATH: "http://plone:8080/Plone"
      PORT: "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8888:8888"
    entrypoint: sh -c "tail -f /dev/null"
    volumes:
      - ./frontend:/opt/frontend/
      # - ./frontend/entrypoint-dev.sh:/opt/fise/entrypoint.sh

  frontend-production:
    image: ${FRONTEND_IMAGE:?no such variable}
    environment:
      API_PATH: "http://localhost:8085/Plone"
      INTERNAL_API_PATH: "http://plone:8080/Plone"
      PORT: "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8888:8888"
    entrypoint: sh -c "tail -f /dev/null"
    volumes:
      - ./frontend:/opt/frontend/

  zeo:
    image: plone:5.2-python2
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
      ZOPE_MODE: "zeo"
    command:
      - zeo

  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
      - "-m"
      - "2048"

# backend demo-forests-p5-plone
# http-request set-path /VirtualHostBase/https/demo-forests-p5.eea.europa.eu:443/fise/VirtualHostRoot/_vh_api/%[path,regsub(\/api,,g)]
